spring:
  datasource:
    url: jdbc:h2:file:~/leffatdb;MODE=PostgreSQL
    username: leffat
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  h2:
    console:
      enable: true
      path: /h2-console
  flyway:
    locations=classpath:db/migration:
